// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClpRlTjYIUfO_b6yKMl62-VMybXRBs304',
    appId: '1:834011281144:web:315bdd3bd40613aaaaed0d',
    messagingSenderId: '834011281144',
    projectId: 'gabrielspaniol-88239',
    authDomain: 'gabrielspaniol-88239.firebaseapp.com',
    storageBucket: 'gabrielspaniol-88239.appspot.com',
    measurementId: 'G-C8J6ECCBJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAe9Yha10lnSakq4fLkYDt3KYqLugdI0qE',
    appId: '1:834011281144:android:3d26e2e0dc126067aaed0d',
    messagingSenderId: '834011281144',
    projectId: 'gabrielspaniol-88239',
    storageBucket: 'gabrielspaniol-88239.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClpRlTjYIUfO_b6yKMl62-VMybXRBs304',
    appId: '1:834011281144:web:26f065fcafc50d22aaed0d',
    messagingSenderId: '834011281144',
    projectId: 'gabrielspaniol-88239',
    authDomain: 'gabrielspaniol-88239.firebaseapp.com',
    storageBucket: 'gabrielspaniol-88239.appspot.com',
    measurementId: 'G-VBPE5FHKHG',
  );
}
